name: Deploy MuleSoft Application Demo
on:
  push:
    branches:
      - hotfix
 
jobs:
  call-workflow:
    uses: Indrajithkatta08/pipeline/.github/workflows/pipeline-hotfix.yml@main
    secrets: inherit
